# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170122_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Env', 'Environment'), ('Tech', 'Technology'), ('Auto', 'Automotive'), ('Otr', 'Others')], default='Env', max_length=1),
            preserve_default=False,
        ),
    ]
