# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170122_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Archive', 'Archive'), ('Hidden', 'Hidden'), ('Projects', 'Projects'), ('Others', 'Others')], default='Blog', max_length=100),
        ),
    ]
